name: Deposit API calls
description: Deposit with Open Journals and Crossref
inputs:
  journal_url:
    description: The url of the journal
    required: true
  journal_secret:
    description: The access token to be used to upload files
    required: true
  issue_id:
    description: The issue number of the submission
    required: true
  crossref_filepath:
    description: The complete filepath of the Crossref XML file
    required: true
  crossref_username:
    description: Crossref username doing the deposit
    required: true
  crossref_password:
    description: Crossref password
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
        cache-version: upload-crossref
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Deposit with Crossref
      id: deposit_crossref
      shell: bash
      env:
        CROSSREF_FILEPATH: ${{ inputs.crossref_filepath }}
        CROSSREF_USERNAME: ${{ inputs.crossref_username }}
        CROSSREF_PASSWORD: ${{ inputs.crossref_password }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/deposit_with_crossref.rb
    - name: Deposit with Open Journals
      id: deposit_OJ
      shell: bash
      env:
        JOURNAL_URL: ${{ inputs.journal_url }}
        JOURNAL_SECRET: ${{ inputs.journal_secret }}
        ISSUE_ID: ${{ inputs.issue_id }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/deposit_with_openjournals.rb
branding:
  icon: archive
  color: green
