name: Deposit API calls
description: Deposit with Open Journals and Crossref

runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
        cache-version: upload-crossref
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}

branding:
  icon: archive
  color: green
